### ISSUE TITLE
Stalled Travis Build 

### ISSUE THREAD

**Issue by bkawk** [PolymerElements/polymer-starter-kit#1129]
### Description
.travis.yml 
```
language: node_js
node_js:
  - "9"
  - "8"
dist: trusty
sudo: required
addons:
  chrome: stable
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - npm run lint
script:
  - xvfb-run npm run test
  - xvfb-run npm run test:integration
```

### Expected outcome

1-2 min build and test

### Actual outcome

10min + build and test

### Live Demo

https://travis-ci.org/bkawk/travis-s3/jobs/471082754

### Steps to reproduce

1. Install the latest polymer starter kit
2. add .travis.yml
