### ISSUE TITLE
Class specificity in media queries

### ISSUE THREAD

**Issue by Frikki** [PolymerElements/polymer-starter-kit#231]
When I in the style, i.e., `app-theme.html`, specify a declaration block, e.g.:

```
.banner {
  background-image: url("../images/home/banner-1@480.jpg");
}
```

it is "compiled" to `.banner:not([style-scope]):not(.style-scope)`.

However, same declaration block within a media query does not get these additional specifications added. For example:

```
@media all and (min-width: 841px) and (max-width: 1280px) and (orientation: landscape) {
  .banner {
    background-image: url("../images/home/banner-1@1280.jpg");
  }
}
```

In effect, this means that the declaration outside the media query gets preferred by the browser, and I would have to manually add the specificity to the declaration block in the media query for it to work as intended.

This feels wrong, and I’d like to hear whether this is supposed to be this way.

**Comment by Frikki** [comment]
I see. Thanks.

**Comment by addyosmani** [comment]
I'm curious whether this is related to https://github.com/Polymer/polymer/issues/2149 (limitation of the CSS custom properties shim that Polymer provides) or is a separate bug to do with the style scoping system. Looping in @kevinpschaaf in case he has some insights on what might be causing the issue.

**Comment by PJay-** [comment]
@addyosmani I don't experience the problem described above by @Frikki 

```css

  .appname {
    color:red;
  }

  @media all and (min-width: 841px) and (max-width: 1280px) and (max-aspect-ratio: 4/3) { 
    .appname {
      color:white;
    } 
  }
```

translates to 

```css
@media (max-aspect-ratio: 4/3) and (max-width: 1280px) and (min-width: 841px)
.appname:not([style-scope]):not(.style-scope) {
    color: white;
}

.appname:not([style-scope]):not(.style-scope) {
    color: red;
}
```
