### ISSUE TITLE
Invisible ripple effect on toolbar buttons

### ISSUE THREAD

**Issue by mikaelharsjo** [PolymerElements/polymer-starter-kit#244]
The refresh and search `paper-icon-buttons` has ripple effect but it's invisible because it uses `--default-primary-color` by default. Same as the default background for `paper-toolbar`. So maybe add something like: 

```css
  paper-toolbar paper-icon-button {
    --paper-icon-button-ink-color: #fff;
  }
```
