### ISSUE TITLE
.paper-font-display1

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/polymer-starter-kit#272]
https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/styles/app-theme.html#L143

For me its very confusing if your app theme is overwriting material design values from paper-styles.

```css
    .paper-font-display1 {
      font-size: 12px;
    }
```

Recommend to style something else to show case instead of overwriting recommended material design styles.
