### ISSUE TITLE
Cannot override application theme variable 

### ISSUE THREAD

**Issue by jgautheron** [PolymerElements/polymer-starter-kit#666]
A quick example:

```css
/* app-theme.html */
:root {
  --light-primary-color: #E0EBF5;
}

.header {
  background: var(--light-primary-color);
  min-height: 370px;
  text-align: center;
}
```

The actual value of the header's background property ends up to be: `#c5cae9`, the original value from `paper-styles/default-theme.html`.
