### ISSUE TITLE
Add auto deploy and test for Google App Engine

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/polymer-starter-kit#676]
Like GitHub Pages and Firebase, add auto deploy and test for Google App Engine.

- [PSK recipe: Deploy to Google App Engine](https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/deploy-to-google-app-engine.md)
- [Travis documentation: Google App Engine Deployment](https://docs.travis-ci.com/user/deployment/google-app-engine)

Maybe @chuckh can help with this? :blush:

**Comment by abdonrd** [comment]
Something like this in the `.travis.yml`?

```yaml
before_deploy:
  - openssl aes-256-cbc -K ...
  - gulp
  - cp app.yaml dist/app.yaml
deploy:
  provider: gae
  project: polymer-starter-kit
  config: dist/app.yaml
  default: true
```
